#!/bin/bash

# boldhumanoid console utility

print_usage()
{
    echo
    echo "boldhumanoid console utility"
    echo
    echo "usage:"
    
    for SCRIPT in bh.d/*; do
        if [ -x ${SCRIPT} ] ; then
            echo
            ${SCRIPT} help
        fi
    done
}


if [[ $# -eq 0 ]] ; then
  print_usage
  exit 1
fi

res=0

if [[ $# == 0 || "$1" == "help" ]] ; then
    print_usage
    exit
fi

SCRIPT="./bh.d/$1"
if [ ! -x ${SCRIPT} ] ; then
    print_usage
    exit
fi

shift
${SCRIPT} $@
