#!/bin/bash

# deploy path N [N ... ]

path=$1

#if [ "$path" != "." ]
#then
#  path="../bundle/${path}"
#fi

# ensure path exists
cd $path
if [ ! -d $path ];
then
  echo "Path '$path' not found"
  exit 1
fi

res=0

for i in ${@:2}
do
  echo deploying $path to darwin$i

  # TODO ensure process isn't running remotely
  ssh darwin@darwin$i "mkdir -p swig && mkdir -p lib/"
  rsync -zrP www motionscripts configuration.json configuration-*.json boldhumanoid.py boldhumanoid boldpy .bash_team darwin@darwin$i:
  rsync -zrP swig/bold.py swig/_bold.so darwin@darwin$i:swig/
  rsync -zrP libwebsockets/lib/libwebsockets.so.4.0.0 darwin@darwin$i:lib/

  if [ $? -ne 0 ]; then
    echo FAILED to deploy to darwin$i
    res=1
  fi
done

cd -

exit $res
