#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh deploy-min N [M...]"
    echo "          deploy boldhumanoid binary and config files to the target robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    echo "deploy-min requires one or more target robot numbers"
    exit 1
fi

for i in ${@:1}
do

    echo deploying to darwin$i.local

    rsync -zrP                            \
        configuration-team.json           \
        configuration-hatfield.json       \
        configuration-drews.json          \
        configuration-iran-open-2014.json \
        configuration-rc2014.json         \
        configuration-metadata.json       \
        boldhumanoid                      \
        darwin@darwin$i.local:

    if [ $? -eq 0 ]; then
        ssh darwin@darwin$i.local 'espeak -p 0 -s 130 -v english-mb-en1 "Minimal deployment complete"' 2> /dev/null &
    else
        echo FAILED to deploy to darwin$i.local
        res=1
    fi

done

exit $res
