#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh deploy-py N [M...]"
    echo "          deploy python files to the target robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    echo "deploy-py requires one or more target robot numbers"
    exit 1
fi

for i in ${@:1}
do
    echo deploying to darwin$i
    
    rsync -zrP \
        boldhumanoid.py \
        boldpy \
        darwin@darwin$i:
    
    if [ $? -ne 0 ]; then
        echo FAILED to deploy to darwin$i
        res=1
    fi
done

exit $res
