#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh deploy N [M...]"
    echo "          deploy all necessary files to the target robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    echo "deploy requires one or more target robot numbers"
    exit 1
fi

for i in ${@:1}
do
    echo deploying to darwin$i
    
    ssh darwin@darwin$i "mkdir -p swig && mkdir -p lib/"
    
    rsync -zrP www \
        motionscripts \
        configuration-team.json \
        configuration-hatfield.json \
        configuration-drews.json \
        configuration-metadata.json \
        boldhumanoid.py \
        boldpy \
        bh \
        bh.d \
        .bash_team \
        boldhumanoid \
        darwin@darwin$i:
    
    rsync -zrP swig/bold.py \
        swig/_bold.so \
        darwin@darwin$i:swig/
    
    rsync -zrP libwebsockets/lib/libwebsockets.so.4.0.0 \
        darwin@darwin$i:lib/
    
    if [ $? -ne 0 ]; then
        echo FAILED to deploy to darwin$i
        res=1
    fi
done

exit $res
