#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh deploy-min N [M...]"
    echo "          deploy boldhumanoid binary and config files to the target robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    echo "Must specify at least one robot number"
    exit 1
fi

# load common functions
if [ ! -f ${BOLD_HUMANOID_DIR}/bh.d/_functions ]; then
    echo "BOLD_HUMANOID_DIR" not set
    exit 1
fi
source ${BOLD_HUMANOID_DIR}/bh.d/_functions

remote_deploy_min()
{
    rsync --quiet --compress              \
        configuration-team.json           \
        configuration-hatfield.json       \
        configuration-drews.json          \
        configuration-rohow2014.json      \
        configuration-metadata.json       \
        boldhumanoid                      \
        darwin@darwin$1.local:

    if [ $? -eq 0 ]; then
        remote_say $1 "Minimal deployment complete"
        report_result $1 0
    else
        report_result $1 1
    fi
}

export -f remote_deploy_min

parallel -j0 remote_deploy_min ::: ${@:1}
