#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh halt N [M...]"
    echo "          shut down the specified robot(s)"
    exit
fi

if [[ $# -lt 1 ]] ; then
    echo "Must specify at least one robot number"
    exit 1
fi

for i in ${@:1}
do
    echo "halting darwin$i" \
        && ssh darwin@darwin$i "sudo halt"

    if [[ $? -ne 0 ]] ; then
        echo FAILED to halt to darwin$i
        res=1
    fi
done

exit $res
