#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh inventory N [M...]"
    echo "          captures an inventory record of robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    echo "inventory requires one or more target robot numbers"
    exit 1
fi

res=0

for i in ${@:1}
do
  echo Capturing inventory record of darwin$i

  ssh darwin$i "echo Data as of \`date\` on \`hostname\`                       \
             && echo                                                           \
             && lsb_release -a 2> /dev/null                                    \
             && echo                                                           \
             && echo ==== FILE SYSTEM ======================================== \
             && echo                                                           \
             && sudo apt-get clean                                             \
             && df -h --type ext4                                              \
             && echo                                                           \
             && sudo du -d 0 -h /home/darwin/log                               \
             && sudo du -d 0 -h /home/darwin/captures                          \
             && sudo du -d 1 -h /home | grep "/home/"                          \
             && sudo du -d 0 -h /boot                                          \
             && echo                                                           \
             && echo ==== NETWORK ============================================ \
             && echo                                                           \
             && echo $ cat /etc/network/interfaces                             \
             && echo                                                           \
             && cat /etc/network/interfaces | grep -v '^\(#\|[[:space:]]*$\)'  \
             && echo                                                           \
             && echo $ cat /etc/hosts                                          \
             && echo                                                           \
             && cat /etc/hosts | grep -v '^\(#\|[[:space:]]*$\)'               \
             && echo                                                           \
             && echo $ ip addr                                                 \
             && echo                                                           \
             && ip addr                                                        \
             && echo                                                           \
             && echo $ ip route                                                \
             && echo                                                           \
             && ip route                                                       \
             && echo                                                           \
             && echo ==== AGENT CONFIGURATION ================================ \
             && echo                                                           \
             && echo $ cat configuration-agent.json                            \
             && echo                                                           \
             && cat ~/configuration-agent.json                                 \
             && echo                                                           \
             && echo ==== SERVICES =========================================== \
             && echo                                                           \
             && echo $ service --status-all                                    \
             && echo                                                           \
             && service --status-all 2>&1                                      \
             && echo                                                           \
             && echo $ initctl list                                            \
             && echo                                                           \
             && initctl list | sed -e 's/, process\s[0-9]*//g' | sort          \
             && echo                                                           \
             && echo ==== LIBRARIES ========================================== \
             && echo                                                           \
             && echo $ ldd boldhumanoid                                        \
             && echo                                                           \
             && ldd boldhumanoid | sed -r 's/\t(.*)\s+\([^)]+\)/\1/g' | sort   \
             && echo                                                           \
             && echo ==== GRUB =============================================== \
             && echo                                                           \
             && echo $ cat /etc/default/grub                                   \
             && echo                                                           \
             && sudo grep -e ^\s*GRUB /etc/default/grub | sort                 \
             && echo                                                           \
             && echo ==== KERNEL ============================================= \
             && echo                                                           \
             && echo $ cat /etc/sysctl.conf                                    \
             && echo                                                           \
             && sudo grep -e ^[^#] /etc/sysctl.conf | sort                     \
             && echo                                                           \
             && echo ==== PACKAGES =========================================== \
             && echo                                                           \
             && echo $ dpkg-query                                              \
             && echo                                                           \
             && dpkg-query -W -f='\${Package;-40}\t\${Installed-Size;8}\t\${Status;1}\t\${Version}\n' | grep -v \"\sd\s\" | sort | cut -f1,2,4-" \
              > $BOLD_HUMANOID_DIR/inventory/temp

  if [ $? -ne 0 ]
  then
    echo FAILED to update to darwin$i
    res=1
    rm $BOLD_HUMANOID_DIR/inventory/temp
  else
    mv $BOLD_HUMANOID_DIR/inventory/temp $BOLD_HUMANOID_DIR/inventory/darwin$i
  fi
done

exit $res
