#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh inventory N [M...]"
    echo "          captures an inventory record of robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    echo "Must specify at least one robot number"
    exit 1
fi

# load common functions
if [ ! -f ${BOLD_HUMANOID_DIR}/bh.d/_functions ]; then
    echo "BOLD_HUMANOID_DIR" not set
    exit 1
fi
source ${BOLD_HUMANOID_DIR}/bh.d/_functions

remote_inventory_capture()
{
  ssh darwin$1 "echo Data as of \`date\` on \`hostname\`                       \
             && echo                                                           \
             && lsb_release -a 2> /dev/null                                    \
             && echo                                                           \
             && echo ==== FILE SYSTEM ======================================== \
             && echo                                                           \
             && sudo apt-get clean                                             \
             && df -h --type ext4                                              \
             && echo                                                           \
             && sudo du -d 0 -h /home/darwin/log                               \
             && sudo du -d 0 -h /home/darwin/captures                          \
             && sudo du -d 1 -h /home | grep "/home/"                          \
             && sudo du -d 0 -h /boot                                          \
             && echo                                                           \
             && echo ==== NETWORK ============================================ \
             && echo                                                           \
             && echo $ cat /etc/network/interfaces                             \
             && echo                                                           \
             && cat /etc/network/interfaces | grep -v '^\(#\|[[:space:]]*$\)'  \
             && echo                                                           \
             && echo $ cat /etc/hosts                                          \
             && echo                                                           \
             && cat /etc/hosts | grep -v '^\(#\|[[:space:]]*$\)'               \
             && echo                                                           \
             && echo $ ip addr                                                 \
             && echo                                                           \
             && ip addr                                                        \
             && echo                                                           \
             && echo $ ip route                                                \
             && echo                                                           \
             && ip route                                                       \
             && echo                                                           \
             && echo ==== AGENT CONFIGURATION ================================ \
             && echo                                                           \
             && echo $ cat configuration-agent.json                            \
             && echo                                                           \
             && cat ~/configuration-agent.json                                 \
             && echo                                                           \
             && echo ==== SERVICES =========================================== \
             && echo                                                           \
             && echo $ service --status-all                                    \
             && echo                                                           \
             && service --status-all 2>&1                                      \
             && echo                                                           \
             && echo $ initctl list                                            \
             && echo                                                           \
             && initctl list | sed -e 's/, process\s[0-9]*//g' | sort          \
             && echo                                                           \
             && echo ==== LIBRARIES ========================================== \
             && echo                                                           \
             && echo $ ldd boldhumanoid                                        \
             && echo                                                           \
             && ldd boldhumanoid | sed -r 's/\t(.*)\s+\([^)]+\)/\1/g' | sort   \
             && echo                                                           \
             && echo ==== GRUB =============================================== \
             && echo                                                           \
             && echo $ cat /etc/default/grub                                   \
             && echo                                                           \
             && sudo grep -e ^\s*GRUB /etc/default/grub | sort                 \
             && echo                                                           \
             && echo ==== KERNEL ============================================= \
             && echo                                                           \
             && echo $ cat /etc/sysctl.conf                                    \
             && echo                                                           \
             && sudo grep -e ^[^#] /etc/sysctl.conf | sort                     \
             && echo                                                           \
             && echo ==== PACKAGES =========================================== \
             && echo                                                           \
             && echo $ dpkg-query                                              \
             && echo                                                           \
             && dpkg-query -W -f='\${Package;-40}\t\${Installed-Size;8}\t\${Status;1}\t\${Version}\n' | grep -v \"\sd\s\" | sort | cut -f1,2,4-" \
              > $BOLD_HUMANOID_DIR/inventory/temp$1

    if [ $? -eq 0 ]
    then
        report_result $1 0
        mv $BOLD_HUMANOID_DIR/inventory/temp$1 $BOLD_HUMANOID_DIR/inventory/darwin$1
    else
        report_result $1 1
        rm $BOLD_HUMANOID_DIR/inventory/temp$1
    fi
}

export -f remote_inventory_capture

parallel -j0 remote_inventory_capture ::: ${@:1}
