#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh move <motion-script> [M...]"
    echo "          play the named motion script on the specified robot(s)"
    exit
fi

if [[ $# -lt 2 ]] ; then
    echo "Must provide a motion script name, and the ID of one or more robots"
    exit 1
fi

res=0
for i in ${@:2}
do
    export NODE_PATH=/usr/local/lib/node_modules

    echo "Running script $1 on darwin$i.local"

    echo "new (require('websocket').client)() \
              .on('connectFailed', function(error) { \
                console.log(error); \
                process.exit(1);
              }) \
              .on('connect', function(conn) { \
                conn.on('error', function(error) { console.log(error); process.exit(1); }); \
                conn.send('{\"type\":\"action\",\"id\":\"motion-script.$1\"}'); \
                conn.close(); \
              }) \
              .connect('ws://darwin$i.local:8080', 'control-protocol');" | node

    if [ $? -ne 0 ]; then
        echo FAILED to move darwin$i
        res=1
    fi
done

exit $res
