#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh mute [N...]"
    echo "          mute the speaker locally, or on the specified robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    amixer set Master mute > /dev/null
    exit
fi

# load common functions
if [ ! -f ${BOLD_HUMANOID_DIR}/bh.d/_functions ]; then
    echo "BOLD_HUMANOID_DIR" not set
    exit 1
fi
source ${BOLD_HUMANOID_DIR}/bh.d/_functions

remote_mute()
{
    ssh darwin@darwin$1.local "amixer set Master mute" > /dev/null

    report_result $1 $?
}

export -f remote_mute

parallel -j0 remote_mute ::: ${@:1}
