#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh query [N...]"
    echo "          query status either locally, or on specified robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    if [ -z $(pgrep -f boldhumanoid) ]
    then
        echo "$(tput setaf 1)Boldhumanoid process is not running locally$(tput sgr 0)"
    else
        echo "$(tput setaf 2)Boldhumanoid process is running locally$(tput sgr 0)"
    fi
    initctl status boldhumanoid
fi

# load common functions
if [ ! -f ${BOLD_HUMANOID_DIR}/bh.d/_functions ]; then
    echo "BOLD_HUMANOID_DIR" not set
    exit 1
fi
source ${BOLD_HUMANOID_DIR}/bh.d/_functions

remote_query()
{
    if [ -z $(ssh darwin@darwin$1.local "pgrep -f boldhumanoid") ]
    then
        if [ $? -ne 0 ]; then
            report_success $1 "process running"
        else
            report_failure $1
        fi
    else
        report_success $1 "NO PROCESS"
    fi
    tput sgr0
}

export -f remote_query

parallel -j0 remote_query ::: ${@:1}
