#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh query [N...]"
    echo "          query status either locally, or on specified robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    if [ -z $(pgrep boldhumanoid) ]
    then
        echo "$(tput setaf 1)Boldhumanoid process is not running locally$(tput sgr 0)"
    else
        echo "$(tput setaf 2)Boldhumanoid process is running locally$(tput sgr 0)"
    fi
fi

res=0
for i in ${@:1}
do
    if [ -z $(ssh darwin@darwin$i.local "pgrep boldhumanoid") ]
    then
        echo "$(tput setaf 1)Boldhumanoid process is not running on darwin$i.local$(tput sgr 0)"
    else
        echo "$(tput setaf 2)Boldhumanoid process is running on darwin$i.local$(tput sgr 0)"
    fi

    ssh darwin@darwin$i.local "echo Data as of \`date\` on \`hostname\` && echo && lsb_release -a && echo && sudo apt-get clean && df -h --type ext4 && echo && sudo du -d 1 -h /home | grep "/home/" && echo && echo /etc/network/interfaces && echo && cat /etc/network/interfaces | grep -v '^\(#\|[[:space:]]*$\)' && echo && echo /etc/hosts && echo && cat /etc/hosts | grep -v '^\(#\|[[:space:]]*$\)' && echo && dpkg-query -W -f='\${Package;-40}\t\${Installed-Size;8}\t\${Status;1}\t\${Version}\n' | grep -v \"\sd\s\" | sort | cut -f1,2,4-" | less

    if [ $? -ne 0 ]; then
        echo FAILED to query for boldhumanoid process on darwin$i.local
        res=1
    fi
done

exit $res
