#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh reboot N [M...]"
    echo "          reboot the specified robot(s)"
    exit
fi

if [[ $# -lt 1 ]] ; then
    echo "Must specify at least one robot number"
    exit 1
fi

# load common functions
if [ ! -f ${BOLD_HUMANOID_DIR}/bh.d/_functions ]; then
    echo "BOLD_HUMANOID_DIR" not set
    exit 1
fi
source ${BOLD_HUMANOID_DIR}/bh.d/_functions

remote_reboot()
{
    ssh darwin@darwin$1.local "sudo reboot"

    remote_reboot $1 $?
}

export -f remote_reboot

parallel -j0 remote_reboot ::: ${@:1}
