#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh scan ADAPTER"
    echo "          scan for network devices on the specified adapter (eg. wlan1)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    echo "Must specify a network adapter (eg. wlan1)"
    exit 1
fi

sudo arp-scan -I $1 -m $BOLD_HUMANOID_DIR/mac-addresses.txt 192.168.123.0/24 192.168.176.0/24 192.168.0.0/24 192.168.103.0/24

exit $?
