#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh setnw ESSID"
    echo "          tell wicd to connect to a specific network and set to automatically connect to it from now on"
    exit
fi

# load common functions
if [ ! -f ${BOLD_HUMANOID_DIR}/bh.d/_functions ]; then
    echo "BOLD_HUMANOID_DIR" not set
    exit 1
fi
source ${BOLD_HUMANOID_DIR}/bh.d/_functions

ESSID=$1

remote_set_wlan_essid()
{
    ssh darwin@darwin$1.local "sudo ./setnw.py $2 && sudo service wicd restart"

    report_result $1 $?
}

export -f remote_set_wlan_essid

parallel -j0 remote_set_wlan_essid {} $1 ::: ${@:2}
