#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh start [N...]"
    echo "          start the boldhumanoid service locally, or on specified robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    sudo start boldhumanoid
    exit $?
fi

for i in ${@:1}
do
    ssh darwin@darwin$i "sudo start boldhumanoid"

    if [ $? -ne 0 ]; then
        echo FAILED to start the boldhumanoid service to darwin$i
        res=1
    fi
done

exit $res
