#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh start [N...]"
    echo "          start the boldhumanoid service locally, or on specified robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    sudo start boldhumanoid
    exit $?
fi

# load common functions
if [ ! -f ${BOLD_HUMANOID_DIR}/bh.d/_functions ]; then
    echo "BOLD_HUMANOID_DIR" not set
    exit 1
fi
source ${BOLD_HUMANOID_DIR}/bh.d/_functions

remote_start()
{
    ssh darwin@darwin$1.local "sudo start boldhumanoid"

    report_result $1 $?
}

export -f remote_start

parallel -j0 remote_start ::: ${@:1}
