#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh stop [N...]"
    echo "          stop the boldhumanoid service locally, or on specified robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    sudo stop boldhumanoid
    exit $?
fi

# load common functions
if [ ! -f ${BOLD_HUMANOID_DIR}/bh.d/_functions ]; then
    echo "BOLD_HUMANOID_DIR" not set
    exit 1
fi
source ${BOLD_HUMANOID_DIR}/bh.d/_functions

remote_stop()
{
   ssh darwin@darwin$1.local "sudo stop boldhumanoid"

    report_result $1 $?
}

export -f remote_stop

parallel -j0 remote_stop ::: ${@:1}
