#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh unmute [N...]"
    echo "          unmute the speaker locally, or on the specified robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    amixer set Master playback 100% unmute > /dev/null
    exit
fi

# load common functions
if [ ! -f ${BOLD_HUMANOID_DIR}/bh.d/_functions ]; then
    echo "BOLD_HUMANOID_DIR" not set
    exit 1
fi
source ${BOLD_HUMANOID_DIR}/bh.d/_functions

remote_unmute()
{
    ssh darwin@darwin$1.local "amixer set Master playback 95% unmute" > /dev/null

    if [ $? -eq 0 ]; then
        remote_say $1 Unmuted
        report_success $1
    else
        report_failure $1
    fi
}

export -f remote_unmute

parallel -j0 remote_unmute ::: ${@:1}
