#!/usr/bin/env bash

if [[ $1 == "help" ]] ; then
    echo "   bh unmute [N...]"
    echo "          unmute the speaker locally, or on the specified robot(s)"
    exit
fi

if [[ $# -eq 0 ]] ; then
    amixer set Master playback 100% unmute > /dev/null
    exit
fi

for i in ${@:1}
do
    ssh darwin@darwin$i.local "amixer set Master playback 95% unmute" > /dev/null

    if [ $? -ne 0 ]; then
        echo FAILED to unmute darwin$i.local
        res=1
    fi
done

exit $res
